config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  resources :orders
  resources :items
  resources :members

  root 'items#index'

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
  belongs_to :user
	accepts_nested_attributes_for :line_items, allow_destroy: true
  after_save :update_total_amount

  def get_amount
    line_items.to_a.sum { |line_item| line_item.quantity * line_item.item.price }
  end
  
  def send_email_for_order_creation
    User.admins.each do |user| 
      NewOrderMailer.send_email_to_admin(user).deliver
    end 
  end

  protected
  
  def update_total_amount
    self.update_column(:total_amount, get_amount)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource
  before_action :load_items, only: [:new, :edit, :show]

  def index
    @orders = @orders.paginate(page: params[:page], per_page: PER_PAGE_LIMIT)
    respond_to do |format|
      format.html
    end
  end

  # GET /orders/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /orders/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # GET /orders/1
  def show
    respond_to do |format|
      format.html
    end
  end

  # PATCH /orders/1
  def update
    respond_to do |format|
      if @order.update_attributes(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated" }
      else
        flash[:error] = @order.errors.full_messages
        load_items
        format.html { render :edit }
      end
    end
  end

  # POST /orders
  def create
    @order.user_id = current_user.id
    respond_to do |format|
      if @order.save
        @order.send_email_for_order_creation
        format.html { redirect_to @order, notice: "Order was successfully created" }
      else
        flash.now[:error] = @order.errors.full_messages
        load_items
        format.html { render :new }
      end
    end
  end

  # DELETE /orders/1
  def destroy
   respond_to do |format|
      if @order.destroy
        format.html { redirect_to orders_path, notice: 'Order was successfully deleted.' }
        format.js
      else
        flash[:error] = @order.errors.full_messages
        format.js
      end
    end
  end

  private

  def order_params
    if params[:action] == "create"
      params.require(:order).permit(:description, line_items_attributes: [:item_id, :quantity, :_destroy])
    else
      params.require(:order).permit(:description, line_items_attributes: [:id, :item_id, :quantity, :_destroy])
    end
  end

  def load_items
    @items = Item.all
  end
end

app/views/orders/_form.html.erb
<!-- spaces issues -->
<%= form_for @order, html:{ id: "order-form" } do |f| %>
<%= render 'shared/errors', object: @order %>
  <div class="row">
    <div class="col">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div> 

    <div class="col">
      <p><strong>Items:</strong></p>
      <div id="line_items">
        <%= f.fields_for :line_items do |line_item| %>
          <%= render 'line_item_fields', f: line_item %>
        <% end %>

        <div class="links">
          <%= link_to_add_association 'add item', f, :line_items %>
        </div>
      </div>
    </div>
  </div></br>

  <%= f.submit %>
<% end %>

app/views/orders/_line_item_fields.html.erb
<div class="nested-fields">
  <%= f.label :item_id %>
  <%= f.select(:item_id, options_from_collection_for_select(@items, 'id', 'name', f.object.item_id)) %>
  <%= f.label :quantity %>
  <%= f.number_field :quantity, required:  true, min: 1 %>
  <%= link_to_remove_association "remove item", f,  data: { confirm: 'Are you sure?' } %>
</div>

app/views/orders/_orders.html.erb
<div class="container jumbotron">
  <h1>Orders</h1>
  <p><%= link_to 'Add order', new_order_path, class: 'btn btn-primary pull-right' %></p><br/>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center">Create By</th>
        <th class="text-center">Description</th>
        <th class="text-center">Number Of Items</th>
        <th class="text-center">Total Amount</th>
        <th colspan="2" class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr id='order_<%= order.id %>'>
          <td><%= link_to order.user.name, member_path(order.user.id) %></td>
          <td ><%= order.description %></td>
          <td class = "table-align-right"><%= order.line_items.count %></td>
          <td class = "table-align-right"><%= number_to_currency(order.total_amount, unit: "PKR ") %></td>
          <td class = 'text-center'><%= link_to 'Show', order %></td>
          <td class = 'text-center'>
            <% if can? :destroy, order %>
              <%= link_to 'Delete', order, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders %>
</div>

app/views/orders/destroy.js.erb
<% if @order.destroyed? %> 
  $("#order_<%= @order.id %>").remove();
<% else %>
  alert ("Some Error Occured!")
<% end %>

app/views/orders/edit.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <h1 class="align-center">Edit Order</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/orders/index.html.erb
<ul><%= render 'orders' %></ul>

app/views/orders/new.html.erb
<div class="container custom-width"">
  <div class="jumbotron">
    <h1 class="align-center">Create New Order</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container jumbotron">
  <% if can? :update, @order %>
    <%= link_to 'Edit order', edit_order_path, class: 'btn btn-primary pull-right' %>&nbsp;
  <% end %>
  <% if can? :destroy, @order %>
    <%= link_to 'Delete', @order, method: :delete,  data: { confirm: 'Are you sure?' }, 
    class: 'btn btn-primary pull-right' %>
  <% end %>
  <h1>Order</h1>
  <div class="mytext text-justify">
    <strong>Description:</strong><br/>
    <%= @order.description %>
  </div>
  <p>
    <strong>Total:</strong>
    <%= @order.total_amount %>
  </p>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center">Item Name</th>
        <th class="text-center">Item Price</th>
        <th class="text-center">Quantity</th>
        <th class="text-center">Total</th>
      </tr>
    </thead>
    <tbody>
      <% @order.line_items.each do |line_item| %>
        <tr>
          <td><%= link_to line_item.item.name, item_path(line_item.item) %></td>
          <td class = "table-align-right"><%= line_item.item.price %></td>
          <td class = "table-align-right"><%= line_item.quantity %></td>
          <td class = "table-align-right"><%= calculate_line_item_total(line_item) %> </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>