config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  resources :orders
  resources :items
  resources :members

  root 'items#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    return true if line_items.empty?
    errors.add(:base, "line_items present")
    return false
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource


  # GET /items
  def index
    @items = @items.paginate(page: params[:page], per_page: PER_PAGE_LIMIT)
    respond_to do |format|
      format.html
    end
  end

  # GET /items/1
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /items/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /items/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # POST /items
  def create
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
      else
        flash[:error] = @item.errors.full_messages
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /items/1
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
      else
        flash[:error] = @item.errors.full_messages
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /items/1
  def destroy
    if @item.destroy
      flash[:notice] = 'Item was successfully deleted.'
    else
      flash[:error] = @item.errors.full_messages
    end
    respond_to do |format|
      format.html { redirect_to items_path }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_for">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
  <div class="form_for">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: 'form-control', required: true, step: 0.1, min: 0%><br/>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/items/_items.html.erb
<div class="container jumbotron custom-width">
  <h1>Items</h1>
  <% if can? :create, Item %>
    <p><%= link_to 'Add Item', new_item_path, class: 'btn btn-primary pull-right' %></p>
  <% end %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center col-sm-2">Item</th>
        <th class="text-center col-sm-2">Price</th>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item %></td>
        <td class = "table-align-right"><%= number_to_currency(item.price, unit: "PKR ") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= will_paginate @items %>

</div>

app/views/items/edit.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <h1>Editing Item</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @item, class: "pull-right"%>
    <span class=pull-right>|</span>
    <%= link_to 'Back', :back, class: "pull-right" %>
  </div>
</div>

app/views/items/index.html.erb
<%= render 'items' %>

app/views/items/new.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <h1>New Item</h1>
    <%= render 'form' %>
    <%= link_to 'Cancel', items_path , class: "pull-right"%>
  </div>
</div>

app/views/items/show.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <p>
      <strong>Name:</strong>
      <%= @item.name %>
    </p>
    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@item.price, unit: "PKR ") %>
    </p>
    <% if can? :update, @item %>
      <%= link_to 'Edit', edit_item_path(@item) %> |
    <% end %>
    <% if can? :destroy, @item %>
      <%= link_to 'Destroy', @item, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <%= link_to 'Back', items_path %>
  </div>
</div>