config/routes.rb
Project::Application.routes.draw do
  devise_for :users

  resources :orders
  resources :items
  resources :members

  root 'items#index'

  

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource class:  "User"

 # GET /members
  def index
    respond_to do |format|
      format.html
    end
  end

  # GET /members/1
  def show
    respond_to do |format|
      format.html
    end
  end

  # GET /members/new
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /members/1/edit
  def edit
    respond_to do |format|
      format.html
    end
  end

  # POST /members
  def create
     respond_to do |format|
      if @member.save
        format.html { redirect_to member_path(@member), notice: 'Member was successfully created.' }
      else
        flash[:error] = @member.errors.full_messages
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH /members/1
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_path(@member), notice: 'Member was successfully updated.' }
      else
        flash[:error] = @member.errors.full_messages
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /members/1
  def destroy
    if @member.destroy
      flash[:notice] = 'Member was successfully deleted.'
    else
      flash[:error] = @member.errors.full_messages
    end
    respond_to do |format|
      format.html { redirect_to members_path }
    end
  end

  private


    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :role_id)
    end
end

app/views/members/_form.html.erb
<!-- variable name -->
<%= form_for @member, url: member_url do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, required: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, required: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
    <%= f.password_field :password, autocomplete: "off", required: true %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", required: true %>
  </div>

  <div class="field">
    <%= f.label :role %><br/>
    <%= f.select(:role_id, User::ROLE_LIST) %>
  </div>

  <div class="actions">
    <br/><%= f.submit "Submit" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="container custom-width"">
  <div class="jumbotron">
    <h1>Editing Member</h1>

    <%= render partial:  'form', locals: { member_url: member_path(@member) } %>

    <%= link_to 'Back', member_path(@member), class: "pull-right"%>
  </div>
</div>

app/views/members/index.html.erb
<div class="container jumbotron">
  <h1>Users</h1>
  <p><%= link_to 'Add User', new_member_path, class: 'btn btn-primary pull-right' %></p>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>
        <td><%= User::ROLE_LIST_HASH.invert[member.role_id] %></td>
        <td><%= link_to 'Show', member_path(member) %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member_path(member), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <h1>New User</h1>
    <%= render partial: 'form', locals: { member_url: members_path } %>
  </div>
</div>

app/views/members/show.html.erb
<div class="container custom-width">
  <div class="jumbotron">
    <p>
      <strong>Name:</strong>
      <%= @member.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @member.email %>
    </p>
    
    <p>
      <strong>Role:</strong>
      <%= User::ROLE_LIST_HASH.invert[@member.role_id].capitalize %>
    </p>



    <%= link_to 'Edit', edit_member_path(@member) %> |
    <%= link_to 'Back', :back %>
  
  </div>
</div>